### ISSUE TITLE
The action doesn't work as expected with version 3.3.0 of EDM

### ISSUE THREAD

**Issue by rahulporuri** [enthought/setup-edm-action#4] opened 2021-12-03 03:54 UTC
It looks like the action doesn't work as expected with the latest version of EDM - 3.3.0. See https://github.com/enthought/traitsui/pull/1785#issuecomment-985193630. The failure is as follows - 

```
Run enthought/setup-edm-action@v1
  with:
    edm-version: 3.3.0
    download-directory: ~/.cache/download
  env:
    INSTALL_EDM_VERSION: 3.3.0
    EDM_ROOT_DIRECTORY: /home/runner/work/traitsui/traitsui/.edm
Using directory for storing downloaded installer: /home/runner/.cache/download
/usr/bin/bash /home/runner/work/_actions/enthought/setup-edm-action/v1/dist/install-edm-linux.sh 3.3.0 /home/runner/.cache/download
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   243    0   243    0     0   1327      0 --:--:-- --:--:-- --:--:--  1327
/home/runner/.cache/download/edm_cli_3.3.0_linux_x86_64.sh: line 1: syntax error near unexpected token `newline'
/home/runner/.cache/download/edm_cli_3.3.0_linux_x86_64.sh: line 1: `<?xml version="1.0" encoding="UTF-8"?>'
(node:1570) UnhandledPromiseRejectionWarning: Error: The process '/usr/bin/bash' failed with exit code 2
    at ExecState._setResult (/home/runner/work/_actions/enthought/setup-edm-action/v1/dist/index.js:1026:25)
    at ExecState.CheckComplete (/home/runner/work/_actions/enthought/setup-edm-action/v1/dist/index.js:1009:18)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/enthought/setup-edm-action/v1/dist/index.js:903:27)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:1022:16)
    at Socket.<anonymous> (internal/child_process.js:444:11)
    at Socket.emit (events.js:314:20)
    at Pipe.<anonymous> (net.js:675:12)
(node:1570) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1570) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by mdickinson** [comment] 2021-12-03 07:39
I suspect the cause is simply that the EDM 3.3.0 installers haven't been uploaded to package-data.enthought.com.

The following command 
```
curl -o edm.pkg https://package-data.enthought.com/edm/osx_x86_64/3.2/edm_cli_3.2.5.pkg
```
works for me. But with:
```
curl -o edm.pkg https://package-data.enthought.com/edm/osx_x86_64/3.2/edm_cli_3.3.0.pkg
```
what's downloaded is an error message:
```
mdickinson@mirzakhani ~ % cat edm.pkg 
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>ZT8F36T7VG4JYPY3</RequestId><HostId>OoJDvfOWIXzE8TPDABaqrZGx1w1P1ue74cbT+M2PoT5m5hYmTfNZM9iO5e+mQ6AGBJplJLWEC+k=</HostId></Error>%                
```

So this is really an EDM release bug, not a setup-edm-action bug. That said, it would be nice if we could modify the action to report more clearly when the target EDM version isn't available.

**Comment by mdickinson** [comment] 2021-12-17 14:56
Closing here. PR #5 should help a bit with the reporting.

**Closed as completed by mdickinson** 2021-12-17 14:56 UTC
